baseurl = "https://blog.sailfishc.cn/"
languageCode = "en-us"
theme = "hello-friend-ng"
enableRobotsTXT = true
enableEmoji = true
googleAnalytics = "UA-124900585-1"
copyright = "sailfish"
defaultContentLanguage = "en"           # Default language to use

[author]                  # essential                     # 必需
  name = "sailfish"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  since = "2017"            # Site creation time          # 站点建立时间

  # Metadata mostly used in document's head
  description = "讨论技术，聊聊生活"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true                                                                            # 是否开启目录
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe            # 是否启用PhotoSwipe（图片可点击）
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [params.logo]
      logoText     = "$ cd /home/"
      logoHomeLink = "/"
  [params.utter]
      repo = "sailfishc/blog-comments"
      issueTerm = "title" #设置每篇文章对应的 issue 的名字，可选 pathname title url，
      theme = "github-dark"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/sailfishcc/"

  [[params.social]]
    name = "email"
    url  = "mailto:sailfishcc@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/sailfishc/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/sailfishc/"


[languages]
  [languages.en]
    title = "橙小张的博客"
    subtitle = "讨论技术，聊聊生活"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd /home/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "about/"
      [[languages.en.menu.main]]
        identifier = "posts"
        name       = "Articles"
        url        = "posts/"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
