baseurl = "https://blog.sailfishc.cn/"
languageCode = "en-us"
theme = "hello-friend-ng"

[params]
  # Metadata mostly used in document's head
  description = "讨论技术，聊聊生活"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [params.logo]
      logoText     = "$ cd /home/"
      logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/sailfishcc/"

  [[params.social]]
    name = "email"
    url  = "mailto:sailfishcc@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/sailfishc/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/sailfishc/"

  [params.utter]
      repo = "https://github.com/Sailfishc/blog-comments"
      issueTerm = "title" #设置每篇文章对应的 issue 的名字，可选 pathname title url，
      theme = "github-dark"

[languages]
  [languages.en]
    title = "橙小张的博客"
    subtitle = "讨论技术，聊聊生活"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd /home/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "about/"
      [[languages.en.menu.main]]
        identifier = "posts"
        name       = "Articles"
        url        = "posts/"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
